name: Generate Permalink

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  permalink:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get commit SHA
        id: commit
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Output permalink
        run: |
          echo "Permalink to this commit:"
          echo "https://github.com/${{ github.repository }}/commit/${{ steps.commit.outputs.sha }}"
